version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"  # Store PostgreSQL data in a local folder
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password # change after logging in
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - "./pgadmin_data:/var/lib/pgadmin"  # Store pgAdmin data in a local folder

